require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - config.ru
    - db/schema.rb
    - bin/*
    - config/*
    - config/*/*
    - Rakefile

Layout/IndentationConsistency:
  Enabled: true

Layout/LineLength:
  Max: 175

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
